-- PROTOCOLO DE SANEAMIENTO DE ESQUEMA v1.0
BEGIN;

-- 1. CORRECCIÓN DE TABLA bff_responsability
ALTER TABLE bff_responsability RENAME TO bff_responsibility;
ALTER TABLE bff_responsibility RENAME COLUMN responsability TO responsibility;
ALTER TABLE bff_responsibility 
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 2. CORRECCIÓN DE TABLA bff_contact
ALTER TABLE bff_contact RENAME COLUMN cyte TO city;
ALTER TABLE bff_contact RENAME COLUMN idcontry TO country_id;
ALTER TABLE bff_contact RENAME COLUMN idresponsability TO responsibility_id;
ALTER TABLE bff_contact RENAME COLUMN idtype TO type_id;
ALTER TABLE bff_contact RENAME COLUMN movil TO mobile;
ALTER TABLE bff_contact 
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- 3. CORRECCIÓN DE TABLA bff_contact_type
ALTER TABLE bff_contact_type 
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

COMMIT;
